version: "3.8"

services:
  server:
    build: holepunchp2p/.
    image: app-dev
    ports: 
      - "5000:5000"
  app:
    container_name: app-dev
    image: app-dev
    build:
      context: .
    volumes:
      - ./src:/app/src
    ports:
      - "3000:3000"
